version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
