version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 10
    groups:
      github-actions-updates:
        patterns:
        - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 10
    groups:
      nuget-updates:
        patterns:
        - "*"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "02:00"
    open-pull-requests-limit: 10
    groups:
      dotnet-sdk-updates:
        patterns:
        - "*"
